import {
  MixerHorizontalIcon,
  ReaderIcon,
  TargetIcon,
  GearIcon,
  StackIcon,
  BarChartIcon,
  LockClosedIcon,
  RocketIcon,
} from "@radix-ui/react-icons";

// Single source of truth for lever configuration
export const leverConfig = {
  "incentive-architecture": {
    id: "strategy",
    slug: "incentive-architecture",
    header: "Strategy",
    name: "Incentive Architecture",
    tagline: "Reward intent. Predict behavior.",
    consequence: "Pull wrong → behavior + cost drift.",
    color: "#F59E0B", // amber
    icon: MixerHorizontalIcon,
    oldPillarKey: "STRATEGY_DESIGN",
    whatItIs: "The design layer that turns company goals into rep behavior—by shaping upside, effort, and tradeoffs.",
    whenToPullBullets: [
      "New product launch, new segment, or margin pressure requiring behavior change",
      "Rep churn, or any quarter where \"behavior feels off\"",
    ],
    commonFailures: [
      "Paying for the wrong thing (activity over outcomes, bookings over profitable bookings)",
      "Hidden cliffs and accidental \"all-or-nothing\" thresholds",
      "Complexity inflation (too many measures, exceptions, or role variants)",
      "Upside that's either meaningless (no motivation) or explosive (budget blowups)",
    ],
    fastWins: [
      "Define a complexity budget (max measures, max exceptions, max payout mechanics)",
      "Replace \"clever math\" with clear curves (show the payout shape, not the formula)",
      "Run 3 mandatory sims: base / stretch / edge-case",
      "Hard-cap any mechanic that can compound unintentionally",
    ],
    evidenceQuestions: [
      "Plan blueprint exists and matches what's paid",
      "Payout curve is visualized (not just formulas)",
      "Scenario pack run pre-launch (base/stretch/edge)",
      "Complexity budget enforced (measure count, exceptions)",
      "Plan changes are versioned with rationale",
    ],
    maturityLadder: [
      { level: 1, name: "Gut feel", desc: "plans are argued, not modeled" },
      { level: 2, name: "Documented", desc: "plan one-pagers + role mapping exist" },
      { level: 3, name: "Simulated", desc: "scenario packs required before launch" },
      { level: 4, name: "Governed", desc: "versioning + change control + evidence chain" },
      { level: 5, name: "Adaptive", desc: "in-quarter signals tune guidance and guardrails" },
    ],
    starterArtifacts: "Plan blueprint • payout curve map • complexity budget • role taxonomy • scenario pack",
    moves: "Pay mix • thresholds • accelerators • role differentiation • complexity budget • upside design",
    blast: "Wrong behaviors • runaway cost • comp compression • retention damage • \"plan cynicism\"",
    scoreboard: "Cost of sale % • pay/performance correlation • payout variance • top-tier attrition • plan exception rate",
    artifacts: "Plan blueprint (one-pager) • role taxonomy • payout curve map • scenario pack (3–5 cases)",
    prevSlug: null,
    nextSlug: "compliance-guardrails",
  },
  "compliance-guardrails": {
    id: "legal",
    slug: "compliance-guardrails",
    header: "Legal",
    name: "Compliance Guardrails",
    tagline: "What you're allowed to do.",
    consequence: "Pull wrong → legal exposure.",
    color: "#38BDF8", // sky
    icon: ReaderIcon,
    oldPillarKey: "LEGAL_REGULATORY",
    whatItIs: "The constraint layer—what you can promise, pay, claw back, and enforce… by jurisdiction and role.",
    whenToPullBullets: [
      "Multi-state growth, reclassifying roles, or new clawback terms",
      "Acquisitions or repeated wage disputes",
    ],
    commonFailures: [
      "Treating commission plans like \"policy docs\" instead of enforceable agreements",
      "Copy/paste clauses that don't survive wage & hour rules",
      "Clawbacks that can't legally be executed",
      "Dispute language that creates ambiguity (and lawsuits)",
    ],
    fastWins: [
      "Audit clawback and forfeiture terms vs. state law",
      "Separate signed plan docs from policy/HR language",
      "Add 409A safe-harbor language if deferrals are involved",
      "Classify roles correctly (exempt vs. non-exempt) and pay accordingly",
    ],
    evidenceQuestions: [
      "Plan document reviewed by employment counsel",
      "Clawback terms are enforceable in all rep states",
      "Role classifications documented (exempt/non-exempt)",
      "Dispute resolution process documented and followed",
      "409A compliance confirmed if deferrals exist",
    ],
    maturityLadder: [
      { level: 1, name: "Verbal", desc: "plans exist as tribal knowledge" },
      { level: 2, name: "Written", desc: "plan docs exist but aren't reviewed" },
      { level: 3, name: "Reviewed", desc: "legal reviews before rollout" },
      { level: 4, name: "Compliant", desc: "state-by-state audit complete" },
      { level: 5, name: "Proactive", desc: "legal monitors regulatory changes" },
    ],
    starterArtifacts: "Plan agreement template • clawback audit • role classification matrix • dispute log",
    moves: "Plan document structure • clawback terms • dispute procedures • role classifications • state compliance",
    blast: "Wage claims • class actions • DOL audits • rep lawsuits • executive liability",
    scoreboard: "Open disputes • dispute resolution time • legal review coverage • compliance exceptions",
    artifacts: "Plan agreement template • state compliance matrix • role classification doc • dispute SOP",
    prevSlug: "incentive-architecture",
    nextSlug: "capacity-coverage",
  },
  "capacity-coverage": {
    id: "planning",
    slug: "capacity-coverage",
    header: "Planning",
    name: "Capacity & Coverage",
    tagline: "Who sells what—and what's possible.",
    consequence: "Pull wrong → unfair quotas + gaps.",
    color: "#22D3EE", // cyan
    icon: TargetIcon,
    oldPillarKey: "SALES_PLANNING",
    whatItIs: "The allocation layer—matching capacity to opportunity, territories to potential, and quotas to attainability.",
    whenToPullBullets: [
      "Annual planning, territory redesign, or headcount changes",
      "New market entry or product launches with different coverage needs",
    ],
    commonFailures: [
      "Quotas set from top-down finance targets, not bottoms-up capacity",
      "Territories drawn by history, not opportunity",
      "No transition rules when accounts move",
      "Headcount changes without quota redistribution",
    ],
    fastWins: [
      "Run quota attainability analysis (what % of reps hit target last 3 years?)",
      "Map territory potential vs. assigned quota",
      "Define account transition rules before changes happen",
      "Create quota redistribution playbook for headcount changes",
    ],
    evidenceQuestions: [
      "Quota methodology documented with data sources",
      "Territory potential analysis exists and is current",
      "Account transition rules defined and followed",
      "Quota attainability tracked (% hitting target)",
      "Headcount change triggers quota review",
    ],
    maturityLadder: [
      { level: 1, name: "Inherited", desc: "quotas rolled from prior year" },
      { level: 2, name: "Top-down", desc: "finance sets, sales divides" },
      { level: 3, name: "Analyzed", desc: "potential and capacity inform quotas" },
      { level: 4, name: "Balanced", desc: "attainability and fairness measured" },
      { level: 5, name: "Dynamic", desc: "in-year adjustments with governance" },
    ],
    starterArtifacts: "Quota methodology doc • territory potential map • transition rules • attainability report",
    moves: "Quota methodology • territory design • account assignment • transition rules • capacity modeling",
    blast: "Unfair quotas • coverage gaps • rep churn • missed pipeline • territory disputes",
    scoreboard: "Quota attainability % • territory balance score • transition disputes • coverage gaps",
    artifacts: "Quota methodology • territory map • account assignment rules • capacity model",
    prevSlug: "compliance-guardrails",
    nextSlug: "systems-spine",
  },
  "systems-spine": {
    id: "technology",
    slug: "systems-spine",
    header: "Technology",
    name: "Systems Spine",
    tagline: "Stop data breaks before payouts do.",
    consequence: "Pull wrong → spreadsheets + distrust.",
    color: "#22C55E", // emerald
    icon: GearIcon,
    oldPillarKey: "TECHNOLOGY_PLATFORMS",
    whatItIs: "The integration layer—how data flows from CRM to payout, and where it breaks.",
    whenToPullBullets: [
      "ICM implementation or replacement",
      "CRM migration, data quality issues, or payout accuracy problems",
    ],
    commonFailures: [
      "ICM treated as \"commission calculator\" instead of data integration hub",
      "No data validation before it hits the comp engine",
      "Shadow systems (spreadsheets) running in parallel",
      "No reconciliation between source systems and payout",
    ],
    fastWins: [
      "Map all data sources feeding the comp engine",
      "Add validation rules at integration points",
      "Kill one shadow spreadsheet per quarter",
      "Build reconciliation report between CRM and ICM",
    ],
    evidenceQuestions: [
      "Data flow diagram exists (source → comp engine)",
      "Validation rules catch bad data before payout",
      "Shadow systems inventory exists and is shrinking",
      "Reconciliation runs before every payout cycle",
      "Data ownership is assigned per source",
    ],
    maturityLadder: [
      { level: 1, name: "Manual", desc: "spreadsheets are the system" },
      { level: 2, name: "Tool", desc: "ICM exists but data is manual" },
      { level: 3, name: "Integrated", desc: "data flows but isn't validated" },
      { level: 4, name: "Validated", desc: "data quality rules enforced" },
      { level: 5, name: "Automated", desc: "end-to-end with exception handling" },
    ],
    starterArtifacts: "Data flow diagram • integration inventory • shadow system list • reconciliation report",
    moves: "ICM selection • integration design • data validation • shadow elimination • reconciliation",
    blast: "Payout errors • rep distrust • audit findings • manual rework • system abandonment",
    scoreboard: "Payout accuracy % • reconciliation exceptions • shadow system count • data latency",
    artifacts: "Data flow diagram • integration spec • validation rules • reconciliation SOP",
    prevSlug: "capacity-coverage",
    nextSlug: "payout-engine",
  },
  "payout-engine": {
    id: "operations",
    slug: "payout-engine",
    header: "Operations",
    name: "Payout Engine",
    tagline: "How money actually moves.",
    consequence: "Pull wrong → late pay + disputes.",
    color: "#F97316", // orange
    icon: StackIcon,
    oldPillarKey: "ICM",
    whatItIs: "The execution layer—calculating, validating, approving, and paying commissions accurately and on time.",
    whenToPullBullets: [
      "Payout accuracy issues, late payments, or dispute volume spikes",
      "New comp plans that stress existing calculation logic",
    ],
    commonFailures: [
      "Calculation logic doesn't match plan document",
      "No pre-payout validation or approval workflow",
      "Disputes handled ad hoc without root cause tracking",
      "Payroll handoff is manual and error-prone",
    ],
    fastWins: [
      "Document the calculation logic for each plan component",
      "Add pre-payout validation checklist",
      "Create dispute intake form with required fields",
      "Automate payroll file generation",
    ],
    evidenceQuestions: [
      "Calculation logic documented and matches plan docs",
      "Pre-payout validation runs every cycle",
      "Disputes tracked with category and root cause",
      "Payout approval workflow exists and is followed",
      "Payroll handoff is automated or has checklist",
    ],
    maturityLadder: [
      { level: 1, name: "Reactive", desc: "fix errors after reps complain" },
      { level: 2, name: "Checked", desc: "spot-check before payout" },
      { level: 3, name: "Validated", desc: "systematic pre-payout review" },
      { level: 4, name: "Governed", desc: "approval workflow with audit trail" },
      { level: 5, name: "Predictive", desc: "anomaly detection before issues" },
    ],
    starterArtifacts: "Calculation spec • validation checklist • dispute tracker • payout calendar",
    moves: "Calculation logic • validation rules • approval workflow • dispute process • payroll integration",
    blast: "Late pay • payout errors • dispute backlog • rep distrust • payroll issues",
    scoreboard: "Payout accuracy % • on-time payout % • dispute volume • resolution time",
    artifacts: "Calculation spec • validation checklist • dispute SOP • payout calendar",
    prevSlug: "systems-spine",
    nextSlug: "signal-forecast",
  },
  "signal-forecast": {
    id: "analytics",
    slug: "signal-forecast",
    header: "Analytics",
    name: "Signal & Forecast",
    tagline: "What's real. What's next.",
    consequence: "Pull wrong → bad calls + missed quarters.",
    color: "#8B5CF6", // violet
    icon: BarChartIcon,
    oldPillarKey: "SALES_INTELLIGENCE",
    whatItIs: "The insight layer—turning comp data into signals for forecasting, planning, and behavior change.",
    whenToPullBullets: [
      "Forecast misses, unexpected cost spikes, or behavior drift",
      "Board/CFO asking questions you can't answer from comp data",
    ],
    commonFailures: [
      "Comp data used for payout only, not insight",
      "No connection between comp signals and revenue forecast",
      "Behavior changes detected after the quarter, not during",
      "Cost forecasts disconnected from attainment projections",
    ],
    fastWins: [
      "Build comp cost forecast tied to attainment scenarios",
      "Create \"behavior drift\" dashboard (payout patterns vs. prior periods)",
      "Add comp signals to weekly sales leadership review",
      "Track leading indicators (pipeline, activity) alongside lagging (payout)",
    ],
    evidenceQuestions: [
      "Comp cost forecast exists and is updated monthly",
      "Behavior drift analysis runs (vs. prior periods)",
      "Comp insights included in sales leadership reviews",
      "Leading indicators tracked alongside payout data",
      "Attainment projections inform revenue forecast",
    ],
    maturityLadder: [
      { level: 1, name: "Blind", desc: "comp data is payout-only" },
      { level: 2, name: "Reported", desc: "dashboards exist but aren't used" },
      { level: 3, name: "Reviewed", desc: "leadership sees comp trends" },
      { level: 4, name: "Integrated", desc: "comp signals inform forecasts" },
      { level: 5, name: "Predictive", desc: "models predict behavior and cost" },
    ],
    starterArtifacts: "Comp cost forecast • behavior dashboard • attainment report • signal deck",
    moves: "Cost forecasting • behavior analytics • attainment tracking • signal integration • predictive models",
    blast: "Forecast misses • cost surprises • behavior drift • blind spots • CFO distrust",
    scoreboard: "Forecast accuracy % • cost variance • behavior trends • signal coverage",
    artifacts: "Cost forecast model • behavior dashboard • attainment tracker • signal deck",
    prevSlug: "payout-engine",
    nextSlug: "controls-evidence",
  },
  "controls-evidence": {
    id: "governance",
    slug: "controls-evidence",
    header: "Governance",
    name: "Controls & Evidence",
    tagline: "Prove it. Audit it. Defend it.",
    consequence: "Pull wrong → findings + liability.",
    color: "#A3E635", // lime
    icon: LockClosedIcon,
    oldPillarKey: "GOVERNANCE_COMPLIANCE",
    whatItIs: "The control layer—policies, approvals, exceptions, and audit trails that prove you're doing it right.",
    whenToPullBullets: [
      "Audit prep, SOX controls, or exception volume spikes",
      "New policies needed (clawback, windfall, termination)",
    ],
    commonFailures: [
      "Policies exist but aren't followed (or can't be proven)",
      "Exceptions approved without documentation",
      "No audit trail from request to payout",
      "Controls designed for audit, not operations",
    ],
    fastWins: [
      "Document the top 5 exception types and approval requirements",
      "Add \"evidence required\" field to exception requests",
      "Build audit trail report from exception request to payout",
      "Review SOX controls for comp and close gaps",
    ],
    evidenceQuestions: [
      "Exception approval policy exists and is followed",
      "Evidence is captured for every exception",
      "Audit trail exists from request to payout",
      "SOX controls documented and tested",
      "Policy exceptions tracked with rationale",
    ],
    maturityLadder: [
      { level: 1, name: "Tribal", desc: "policies are verbal or ignored" },
      { level: 2, name: "Written", desc: "policies exist but aren't enforced" },
      { level: 3, name: "Followed", desc: "policies enforced with exceptions" },
      { level: 4, name: "Evidenced", desc: "audit trail proves compliance" },
      { level: 5, name: "Controlled", desc: "SOX-grade controls with testing" },
    ],
    starterArtifacts: "Exception policy • approval matrix • audit trail report • SOX control doc",
    moves: "Policy definition • approval workflow • evidence capture • audit trail • SOX controls",
    blast: "Audit findings • SOX deficiencies • fraud exposure • liability • exception chaos",
    scoreboard: "Exception volume • approval compliance % • audit findings • control test results",
    artifacts: "Exception policy • approval matrix • audit trail • SOX control documentation",
    prevSlug: "signal-forecast",
    nextSlug: "enablement-loop",
  },
  "enablement-loop": {
    id: "enablement",
    slug: "enablement-loop",
    header: "Enablement",
    name: "Enablement Loop",
    tagline: "Make it understood. Make it stick.",
    consequence: "Pull wrong → confusion + gaming.",
    color: "#F43F5E", // rose
    icon: RocketIcon,
    oldPillarKey: "IMPLEMENTATION_CHANGE",
    whatItIs: "The adoption layer—communication, training, and feedback loops that turn plans into understood behavior.",
    whenToPullBullets: [
      "Plan rollouts, mid-year changes, or rep confusion spikes",
      "New hire onboarding or manager enablement gaps",
    ],
    commonFailures: [
      "Plans rolled out with no communication or training",
      "Reps learn plans from each other (incorrectly)",
      "No feedback loop from field to comp team",
      "Managers can't explain plans to their teams",
    ],
    fastWins: [
      "Create plan summary one-pager for each role",
      "Run \"plan quiz\" at rollout to test understanding",
      "Add feedback channel from reps to comp team",
      "Train managers to explain plans (not just reps)",
    ],
    evidenceQuestions: [
      "Plan summary exists for each role",
      "Rollout training completed and tracked",
      "Rep feedback channel exists and is monitored",
      "Manager enablement completed",
      "Understanding validated (quiz, certification)",
    ],
    maturityLadder: [
      { level: 1, name: "Dropped", desc: "plans emailed with no context" },
      { level: 2, name: "Presented", desc: "all-hands deck, no follow-up" },
      { level: 3, name: "Trained", desc: "training delivered, not validated" },
      { level: 4, name: "Validated", desc: "understanding tested and tracked" },
      { level: 5, name: "Continuous", desc: "feedback loop improves next cycle" },
    ],
    starterArtifacts: "Plan one-pager • training deck • feedback form • manager guide",
    moves: "Communication plan • training design • feedback loops • manager enablement • validation",
    blast: "Rep confusion • gaming behavior • manager frustration • adoption failure • trust erosion",
    scoreboard: "Training completion % • quiz scores • feedback volume • confusion ticket rate",
    artifacts: "Plan one-pager • training materials • feedback tracker • manager enablement guide",
    prevSlug: "controls-evidence",
    nextSlug: null,
  },
} as const;

// Export ordered array for iteration
export const leverOrder = [
  "incentive-architecture",
  "compliance-guardrails",
  "capacity-coverage",
  "systems-spine",
  "payout-engine",
  "signal-forecast",
  "controls-evidence",
  "enablement-loop",
] as const;

export type LeverSlug = (typeof leverOrder)[number];
export type LeverConfig = (typeof leverConfig)[LeverSlug];

// Helper to get lever by old pillar key
export function getLeverByPillarKey(pillarKey: string): LeverConfig | undefined {
  return Object.values(leverConfig).find((lever) => lever.oldPillarKey === pillarKey);
}

// Helper to get color by old pillar key
export function getLeverColorByPillarKey(pillarKey: string): string {
  const lever = getLeverByPillarKey(pillarKey);
  return lever?.color || "#64748B";
}
